import numpy as np
import matplotlib.pyplot as plt
import tikzplotlib

spot = np.linspace(start = 0, stop = 100, num = 1000)
K = 50
call = np.maximum(spot - K, 0)
put = np.maximum(K - spot, 0)

fig = plt.figure(figsize=(20, 10), dpi = 200)
ax = fig.add_subplot(121)
ax2 = fig.add_subplot(122)
ax.plot(spot, call, linewidth=2)
ax.spines["left"].set_position(("data", 0))
ax.spines["bottom"].set_position(("data", 0))
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.set_title("Payoff of a call option")
ax.set_xlabel(r'$S_T$', ha = "right")
ax.set_ylabel(r'$c_T$', rotation="horizontal")
ax.set_xticklabels([])
ax.set_yticklabels([])
ax.annotate("K", (50, 0), xytext = (0,-20), textcoords="offset points")
ax.xaxis.set_label_coords(1, 0)
ax.yaxis.set_label_coords(0, 1)
ax.plot(1, 0, ">k", transform=ax.get_yaxis_transform(), clip_on=False)
ax.plot(0, 1, "^k", transform=ax.get_xaxis_transform(), clip_on=False)

ax2.plot(spot, put, linewidth=2)
ax2.spines["left"].set_position(("data", 0))
ax2.spines["bottom"].set_position(("data", 0))
ax2.spines["top"].set_visible(False)
ax2.spines["right"].set_visible(False)
ax2.set_title("Payoff of a put option")
ax2.set_xlabel(r'$S_T$', ha = "right")
ax2.set_ylabel(r'$p_T$', rotation="horizontal")
ax2.set_xticklabels([])
ax2.set_yticklabels([])
ax2.annotate("K", (50, 0), xytext = (0,-20), textcoords="offset points")
ax2.xaxis.set_label_coords(1, 0)
ax2.yaxis.set_label_coords(0, 1)
ax2.plot(1, 0, ">k", transform=ax2.get_yaxis_transform(), clip_on=False)
ax2.plot(0, 1, "^k", transform=ax2.get_xaxis_transform(), clip_on=False)
plt.savefig("options.png")